# Generated by Django 3.2.10 on 2023-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('mother', models.CharField(max_length=15)),
                ('employe_id', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=13)),
                ('b_day', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
