# Generated by Django 4.2.1 on 2023-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studinfo', '0003_alter_sinfo_b_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinfo',
            name='password',
        ),
        migrations.AlterField(
            model_name='sinfo',
            name='b_day',
            field=models.DateField(),
        ),
    ]
