# Generated by Django 3.2.10 on 2023-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studinfo', '0004_remove_sinfo_password_alter_sinfo_b_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
