# Generated by Django 4.2.1 on 2023-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt',
            name='stand',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
