# Generated by Django 4.2.1 on 2023-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_tt_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt',
            name='time',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='tt',
            name='stand',
            field=models.CharField(max_length=50),
        ),
    ]
