# Generated by Django 4.2.1 on 2023-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_sinfo_delete_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('Monday', models.CharField(max_length=50)),
                ('Tuesday', models.CharField(max_length=50)),
                ('Wednesday', models.CharField(max_length=50)),
                ('Thursday', models.CharField(max_length=50)),
                ('Friday', models.CharField(max_length=50)),
                ('Saturday', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='sinfo',
        ),
    ]
