# Generated by Django 3.2.10 on 2024-01-18 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('class_div', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True)),
                ('complaint', models.CharField(max_length=500)),
                ('complaint_date1', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
