# Generated by Django 3.2.10 on 2024-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmodel',
            name='complaint_date1',
            field=models.DateField(null=True),
        ),
    ]
