# Generated by Django 3.2.10 on 2024-01-18 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_compmodel_complaint_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmodel',
            name='complaint_date1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
