# Generated by Django 3.2.10 on 2024-01-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_compmodel_complaint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmodel',
            name='complaint_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
