# Generated by Django 3.2.10 on 2024-01-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_compmodel_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmodel',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
