# Generated by Django 3.2.10 on 2024-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_compmodel_complaint_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compmodel',
            name='complaint_time',
        ),
        migrations.AddField(
            model_name='compmodel',
            name='complaint_dateT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
