# Generated by Django 3.2.10 on 2024-01-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_compmodel_complaint_datet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmodel',
            name='complaint_dateT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
