# Generated by Django 3.2.10 on 2024-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_remove_compmodel_complaint_datet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompModelN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('class_div', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True)),
                ('complaint', models.CharField(max_length=500)),
                ('complaint_dateT', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='compmodel',
            name='complaint_dateT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
