# Generated by Django 3.2.10 on 2024-01-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_auto_20240119_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compmodel',
            name='complaint_dateT',
        ),
    ]
