# Generated by Django 3.2.10 on 2024-01-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_remove_compmodel_complaint_datet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompModelN',
        ),
    ]
