# Generated by Django 3.2.10 on 2023-07-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sattand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attandmod',
            old_name='roll_no1',
            new_name='roll_no',
        ),
    ]
