# Generated by Django 3.2.10 on 2023-07-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sattand', '0002_rename_roll_no1_attandmod_roll_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attandmod',
            new_name='attandmodNEW',
        ),
    ]
